### PR TITLE
ArduinoHA 2.0.0 🔥

### PR DESCRIPTION
**Pull request by dawidchyrzynski**
I'm currently working on a new major version of the library that's basically a ground refactor of the previous implementation. The main goal of this branch was to refactor the way how entities are serialized in order to simplify and standardize the codebase.

In order to improve the general quality of the library, I have decided to cover each part of the library with unit tests and write detailed documentation describing the library in each tiny detail.

Stay tuned ✌️

### CODE REVIEW

**Comment by dawidchyrzynski** [comment]
@netmindz The branch is still a work in progress. Some of the entities are not implemented yet (like HASensor).

**Comment by netmindz** [comment]
Roughly what % are you through this rewrite? Wondering if it's worth me trying to get my much smaller patch to handle selective update working. It's real pain in the arse in your main project to litter with code to keep track there of if the value has changed before calling update

**Comment by dawidchyrzynski** [comment]
@netmindz The rewrite is finished in 80%. Can you explain what you exactly want to achieve?

**Comment by netmindz** [comment]
@dawidchyrzynski HABinarySensor::setState only actually sends message if new value != previous value, so in your code of you main app you can just call setState and be sure that you will get immediate MQTT if the value changes. Last update time in HA is the same as last state change.

This is only for the BinartSensor, my PR tried to make that the same for other sensor types too.

Without this you either flood MQTT with the same value over and over, have to put the actual update values all in block of code within your main loop that only triggers every X seconds (adding lag to responsiveness) or for every value you want to manage, have code like the following

if(temp != previousTemp) {
  tempSensor.setState(temp);
  previousTemp = temp;
}

Which clearly gets messy very quickly

E.g https://github.com/netmindz/balboa_GL_ML_spa_control/blob/1b5fcb801037b1ef099e013904b7514a399c63bb/sensor/sensor.ino#L522

**Comment by dawidchyrzynski** [comment]
@netmindz This PR introduces a new implementation for the sensor entity. You can checkout into the `serializer-refactor` branch and try a new implementation. Basically, the sensor will be split into three different classes:
- HASensor - textual sensor (no data retention)
- HASensorInteger - integer numbers (with data retention - comparing states)
- HASensorFloat - floating point numbers (with data retention - comparing states)

This implementation provides the smallest utilization of the RAM and flash. Here is the changelog that describes all breaking changes in the API: https://github.com/dawidchyrzynski/arduino-home-assistant/blob/serializer-refactor/CHANGELOG.md

Alternatively if it doesn't meet your requirements you can wrap the HASensor (or any other class) with your own class and implement the logic you need. For example:

```cpp
class MySensor {
public:
    MySensor(): _sensor("uniqueName") {
        _sensor.setName("Pretty name");
        _sensor.setIcon("mdi:home");
    }

    void doSomeStuff() {
        // some custom logic
    }
private:
    HASensor _sensor;
};

```

**Comment by patryk-zielinski93** [comment]
I am trying to create my own smart home, fortunately I found this library, because it allows me to significantly reduce the programming time of my own smart home based on arduino. I am very grateful and I hope you will continue the great work you are doing. I'm looking forward to the new release because it looks very promisnig. Are you planning to support HALight? Are you able to say how much time you need to complete the release?

**Comment by dawidchyrzynski** [comment]
Hi @patryk-zielinski93,

The new version is going to support all available device types, including HALight. I think the realistic date for the release is early December.

**Comment by dawidchyrzynski** [comment]
@d-a-v It looks interesting. I will have a look at this once the main work is finished. Can you comment the HADevice.cpp:45 line and try to build the lib again?

**Comment by d-a-v** [comment]
The error disappeared :+1:

On termination, there are 4 leaks, 3 of them come from the mocking subsystem, the 4th is detailed below.


```
==2630715== 
==2630715== HEAP SUMMARY:
==2630715==     in use at exit: 325 bytes in 4 blocks
==2630715==   total heap usage: 32 allocs, 28 frees, 2,249,513 bytes allocated
==2630715== 
==2630715== 13 bytes in 1 blocks are still reachable in loss record 1 of 4
==2630715==    at 0x4844293: operator new[](unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2630715==    by 0x13BA3D: HAUtils::byteArrayToStr(unsigned char const*, unsigned short) (HAUtils.cpp:44)
==2630715==    by 0x13468F: HADevice::setUniqueId(unsigned char const*, unsigned short) (HADevice.cpp:55)
==2630715==    by 0x10DED2: setup (nodemcu.ino:29)
==2630715==    by 0x10F478: main (ArduinoMain.cpp:308)
```

Once again, this is not to blame anyone or a work-in-progress particularly.
On top of that, on Arduino, some buffers may be allocated and never released anyway.
What's interesting is that mocking environments and valgrind help debugging mcu code.
Speaking of esp8266, this one was designed for CI originally, and later helped to debug internal and external network libraries, like yours is.

**Comment by dawidchyrzynski** [comment]
@d-a-v This memory leak is caused by the line you just commented. Can you try to uncomment it and replace it with `delete[] _uniqueId;`. It should still build and fix the leak :)

**Comment by dawidchyrzynski** [comment]
@d-a-v Also please make sure you're working on the latest commit. I was fixing memory leaks yesterday so maybe the problem you found is already solved.

**Comment by d-a-v** [comment]
This indeed solved both issues :+1:
(using current version of this PR)

```diff
diff --git a/src/HADevice.cpp b/src/HADevice.cpp
index 4642fda..e30416d 100644
--- a/src/HADevice.cpp
+++ b/src/HADevice.cpp
@@ -42,7 +42,7 @@ HADevice::~HADevice()
     }
 
     if (_ownsUniqueId) {
-        delete _uniqueId;
+        delete [] _uniqueId;
     }
 }
```

**Pull request merged**
