### PR TITLE
Add support for state_class property to sensors

### PR DESCRIPTION
**Pull request by tjoneseng**
Per https://www.home-assistant.io/more-info/statistics/ this enables them for use with the Statistics Graph card.

### CODE REVIEW

**Comment by dawidchyrzynski** [comment]
This feature will be implemented as part of the #81

**Comment by tjoneseng** [comment]
Not maintaining this any longer?

**Comment by dawidchyrzynski** [comment]
@tjoneseng I'm working on the large refactor of the library. It will be released soon this year.

**Comment by Kobbe1** [comment]
@dawidchyrzynski 
Unfortunately I can't find wether this is now implemented in 2.0.0 or will come later? I tried searching source, examples and documentation but cant find any reference to "state_class" apart from this and a few more issues.

**Pull request closed without merging**
