### PR TITLE
Added the most basic light support

### PR DESCRIPTION
**Pull request by solarkennedy**
For #10. This adds the most basic light support.
It isn't much more than a switch honestly, but it
can be toggled off and on.

Future work can include RGB and brightness levels,
but this PR just is the initial scaffolding.

### CODE REVIEW

**Comment by d-a-v** [comment]
Hello, did you plan to add an `examples/light/` for this new light support ?

**Comment by solarkennedy** [comment]
Added.

**Comment by rickvanelk** [comment]
Will this pull request be accepted or is this repo not maintained anymore? 
I wanted to add the RGB and Brightness levels as well.

**Comment by dawidchyrzynski** [comment]
I'm closing the PR as there is a new major version of the lib coming that includes this feature - see #81

**Pull request closed without merging**
